title: Jarrett Wendt
iconURL: /assets/default-icon.png
404iconURL: /assets/404-icon.png

markdown: kramdown

future: true

# for a clean URL
permalink: :slug

resume: /assets/resume.pdf
repo: https://github.com/JarrettWendt/FIEAEngine

social:
  email: wendtjarrett@gmail.com
  linkedin: https://linkedin.com/in/jarrett-wendt
  github: https://github.com/JarrettWendt

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections_dir: collections
collections:
  projects:
    output: true
  custom_engine:
    output: true
  misc_blog:
    output: true

header_pages:
  - pages/projects.md
  - pages/blog.md
  - pages/contact.md

### comments & analytics
# hyvor_talk_website_id: 14
# google_analytics: UA-NNNNNNNN-N
